ARMmbed/icetea

- icetea_lib/DeviceConnectors/DutProcess.py
**READY**
Removed DutProcess exit command that is specific to certain applications.
> Removed application specific exit command.

- setup.py
> version 1.0.0 rc4

- setup.py
**READY**
Version number is now v1.0.0
> Updated version number to v1.0.0

- setup.py
**READY**
NO
Updapte version for next patch release
> increase patch number for next release

- icetea_lib/Plugin/plugins/LocalAllocator.py
- icetea_lib/Plugin/plugins/plugin_tests/test_localallocator.py
**READY**
A few sentences describing the overall goals of the pull request's commits.
https://github.com/ARMmbed/icetea/issues/39
> Raising an allocation error if enough hardware devices not available

- .circleci/config.yml
- setup.py
**READY**
NO
Adding circleci configuration and more environment to be test
> circleci 2 file

- .circleci/config.yml
- .coveragerc
**READY**
Use requirements files for dependency installation in circle.
> Use requirements files for dependencies in ci.

- setup.py
**READY**
NO
Update version number for next patch rel
> update version number for next patch rel

- .circleci/config.yml
**READY**
CircleCI tests didn't run default plugin tests.
> Added plugin tests to circleci tests.

- icetea_lib/cloud.py
- icetea_lib/tools/tools.py
- test/test_cloud.py
**READY**
Added support for logging cloud module version. Some pylint fixes, primarily added some missing docstrings, included in the same  commit.
> Support printing cloud module version.

- setup.py
> v1.1.0 release candidate 1

- setup.py
**READY**
Fix an installation problem with rc1 with rc2.
> Change to v1.1.0-rc2

- icetea_lib/ResourceProvider/ResourceRequirements.py
- icetea_lib/tc_schema.json
- setup.py
- test/test_resourcerequirements.py
**READY**
Added some more resource requirement fields.
> Added tags and some other schema fields.

- icetea_lib/arguments.py
> Fix argument typo buggers to buffers.

- dev_requirements.txt
- extra_requirements.txt
- requirements.txt
- setup.py
**READY**
Pin major versions of our requirements in our requirements.txt and setup.py files. Related to issue #69.
> Pin major versions wherever we can.

- icetea_lib/LogManager.py
**READY**
Disabled logger message propagation from base level loggers to mitigate possible issues with other modules which might give the root logger handlers.
> Disabling logger message propagation for base level loggers.

- doc-source/Icetea.rst
- doc/Icetea.md
- icetea_lib/DeviceConnectors/Dut.py
- icetea_lib/TestBench/Resources.py
- icetea_lib/arguments.py
- test/test_dut.py
**READY**
Support cli synchronization using sync_start argument and the echo command.
Tests and the implementation already exist in the base branch, just the argument to enable the feature was missing.
> Support sync_start argument for synchronizing device cli.

- requirements.txt
- setup.py
> update mbed-flasher dependency to latest one

- pipeline.groovy
- requirements.txt
- setup.py
**READY**
Certain older jsonmerge versions restrict the jsonschema version to a really old one. Let's restrict to a set of versions that support the newer ones.
Also use virtualenvs in coverage runs on both windows and unix.
> Update jsonmerge version requirement

- doc-source/plugin_framework.rst
- doc/plugin_framework.md
- icetea_lib/DeviceConnectors/Dut.py
- test/test_dut.py
**READY**
Add api for checking if a dut has died during the wait loop. Each dut should implement their own version of this if necessary.
> Added api to check if dut is alive for Dut object.

- setup.py
**READY**
Updating version number.
> Updated version number to v1.2.2

- icetea_lib/LogManager.py
- icetea_lib/TestBench/Configurations.py
- icetea_lib/TestSuite/TestcaseContainer.py
- icetea_lib/tools/GenericProcess.py
- icetea_lib/tools/HTTP/Api.py
- test/test_genericprocess.py
**READY**
Use SIGINT and SIGTERM before SIGKILL when stopping process type duts.
> Try more signals for killing process type duts.

- icetea_lib/TestBench/Bench.py
**READY**
Fixed a return code print.
> Fixing a return code print in test bench.

- icetea_lib/TestBench/Resources.py
- test/test_bench_resources.py
**READY**
Fixed an issue that caused release to not be called when an exception occurs in close_dut or close_connection at the end of a test case.
> Fixed an issue in dut releasing

- icetea_lib/ResultList.py
- icetea_lib/TestSuite/TestSuite.py
- test/test_testsuite.py
**READY**
Save html and Junit reports between each test case.
> Save results between each test case

- icetea_lib/ResultList.py
- icetea_lib/ReturnCodes.py
- icetea_lib/TestBench/BenchApi.py
- icetea_lib/TestBench/Results.py
- icetea_lib/TestSuite/TestSuite.py
- icetea_lib/TestSuite/TestcaseContainer.py
- test/test_bench.py
- test/test_testcasecontainer.py
- test/test_testsuite.py
**READY**
Better support returning Resultlist as a result from a test.
> Better support Resultlist as result from tc.

- setup.py
**READY**
Release candidate 1 of 2.0.0.
> rc1 of 2.0.0

- setup.py
**READY**
Update version number.
> Version number update.

- setup.py
**READY**
Update version number to release candidate.
> Tag rc1 of v2.0.1

- setup.py
**READY**
Updated version number.
> Version number updated to v2.0.1
